### ISSUE TITLE
Check mods required jötunn version

### ISSUE THREAD

**Issue by sirskunkalot** [Valheim-Modding/Jotunn#118]
Inject the jötunn version a mod is built with into it and check for that on game load. if a mod was built with / needs another version of jötunn articulate that somehow. so the user can be aware of possible compat issues.

**Comment by Algorithman** [comment]
BepInEx has a built-in option for a minimum version for mod dependencies.
If we use that, we lose the option to present the error on screen, since BepInEx won't load the mod and only writes some warnings in the console window.

**Comment by paddywaan** [comment]
> BepInEx has a built-in option for a minimum version for mod dependencies.
> If we use that, we lose the option to present the error on screen, since BepInEx won't load the mod and only writes some warnings in the console window.

Sure, however instead of providing warning, it provides assurance instead, which is arguably better? Furthermore, this isn't within our realm of responsibility, since it requires the plugin dev themselves to specify their plugin requirements?

**Comment by sirskunkalot** [comment]
I would be fine with the BepInEx version. It is really just to present a warning if a user installs two mods with different Jötunn versions so if issues come up, we can say: "Look, console told you so"

**Comment by sirskunkalot** [comment]
(BepInEx soft dependance would load anyway, right?)

**Comment by sirskunkalot** [comment]
And: I am with paddy here that is the responsibility of the mod dev in the end. They would also be in charge of updating the mod to use the others mods jötunn version.

**Comment by paddywaan** [comment]
If we agree with this way forward, we should include an example of version dependencies, to help inform users.

**Comment by sirskunkalot** [comment]
But then again if Jötunn does inject its version into the mod during compile we could at least be sure that it really was the version the mod was compiled against. Otherwise mod devs could just leave the version out. dunno...

**Comment by Algorithman** [comment]
Since we don't have a mechanism to target feature sets inside JVL, i think a default setting to the latest JVL version in the modstub/example would be best.
If the mod does not use the newest JVL features, the developer still can lower the version requirement himself.
Injecting the latest version should pose no problem, can be done in the stub/example GH action.

**Comment by paddywaan** [comment]
So, this should ideally be a v1.1 implementation of R2API's SubModule system, which allowed types (managers) to be specified as dependencies by plugins using attributes. this allowed the library to only load the modules required to interact with each games collection/interface, and also increased durability of the lib in regards to patch days, as some mods would only be using non-updated submodules which still work as intended.
