### ISSUE TITLE
Convert iDeath's example mod to JVL for unity example

### ISSUE THREAD

**Issue by paddywaan** [Valheim-Modding/Jotunn#123]
Convert the project so that we can link to it in unity.md on the GH pages example. Tutorial for unity will be confusing without it?

**Comment by paddywaan** [comment]
@raduschirliu think this is something you can handle? I'm swamped with documentation D:

**Comment by D-first** [comment]
Hey there, I'm attempting to contribute for the first time.
I have forked iDeath's Lead mod and modified it to use JVL.
Does this help?

https://github.com/D-first/Lead/tree/convert-jvl

**Comment by paddywaan** [comment]
nice, now submit a [PR](https://github.com/Valheim-Modding/ExampleMod/pulls)

**Comment by D-first** [comment]
You mean a PR for JotunnModExample, right?
In that case, how should I do putting Lead mod in the repository of JotunnModExample?

**Comment by paddywaan** [comment]
No, just PR it back to where you forked it from and I'll take a look.

**Comment by D-first** [comment]
I understand thank you.

**Comment by sirskunkalot** [comment]
A PR was made, needs review/merge and docs. https://github.com/xiaoxiao921/Lead/pull/5

**Comment by sirskunkalot** [comment]
merged...
