### ISSUE TITLE
Refactor SkillManager / SkillPatches

### ISSUE THREAD

**Issue by sirskunkalot** [Valheim-Modding/Jotunn#137]

**Comment by sirskunkalot** [comment]
@raduschirliu is there anything that stops us from integrating the last patches into the manager? if not i would do this and delete the patches class... and close this issue

**Comment by raduschirliu** [comment]
@sirskunkalot I don't think there would be any issue with doing that? At least, there are none that I can think of right now. If you have some time, sure, go for it! :)
