### ISSUE TITLE
SkillConfig throws errors if UID is negative

### ISSUE THREAD

**Issue by raduschirliu** [Valheim-Modding/Jotunn#14]
Not sure if this is an issue or not yet, but wanted to repost an issue raised on one of the PRs on the JotunnLib repo:
https://github.com/jotunnlib/jotunnlib/pull/21

It appears that some strings can have a negative hash code, which then results in a negative SkillConfg UID (used for Skill.SkillType).

EDIT: It appears it throws errors on negative UID. With the errors fixed, negative UIDs seem to work just fine :)

**Comment by farefray** [comment]
could be reproduced with string "farefray.valheim.JustAnotherCookingSkill"
