### ISSUE TITLE
Implement Submodules

### ISSUE THREAD

**Issue by paddywaan** [Valheim-Modding/Jotunn#146]
see [R2API](https://github.com/risk-of-thunder/R2API/blob/master/R2API/Utils/APISubmodule.cs) for submodule implementation. Facilitates dynamic loading of dependant libraries which increases robustness on patchdays, and negates instant, community-wide failure due to 1 single change.

**Comment by xiaoxiao921** [comment]
This may be hard /annoying to do now that we released a version of JVL on stores, meaning that old mods will have to switch to use the submodules instead
