### ISSUE TITLE
[FEATURE]  Zonemanager ( custom locations,biomes)

### ISSUE THREAD

**Issue by Shuwa** [Valheim-Modding/Jotunn#156]
we could need more love for the Zonemanager!!
adding custom prefab locations into biomes
make completly new biomes with custom prefab vegetaion, landtexturelayers etc.

but also want to say thanks great work boys!
pushing the Valheim Modding Scene to the next Level with your awesome Libary.

**Comment by paddywaan** [comment]
Thanks!

Sure, we have plans for the ZoneManager, however they will not be making it into v1.0.

**Comment by sirskunkalot** [comment]
closed by #311
