### ISSUE TITLE
Documentation for adding pieces

### ISSUE THREAD

**Issue by raduschirliu** [Valheim-Modding/Jotunn#161]
There is currently no documentation around how to add custom pieces or piece tables. A lot of this has remained the same from JL, so these could likely be taken from the JL docs:
https://jotunnlib.github.io/jotunnlib/tutorials/data/pieces.html
https://jotunnlib.github.io/jotunnlib/tutorials/data/piece-tables.html

**Comment by sirskunkalot** [comment]
Hmm, there is actually: https://valheim-modding.github.io/Jotunn/tutorials/data/pieces.html

But the toc.yml is buggy: https://github.com/Valheim-Modding/Jotunn/blob/dev/JotunnLib/Documentation/tutorials/data/toc.yml#L25

I correct it and push to prod
