### ISSUE TITLE
Can ConsoleCommands be made public?

### ISSUE THREAD

**Issue by ngregrichardson** [Valheim-Modding/Jotunn#18]
I'd like to check if a custom command has already been loaded, but the list of loaded console commands is [marked as internal](https://github.com/Valheim-Modding/Jotunn/blob/dev/JotunnLib/Managers/CommandManager.cs#L27). Is this something that can/should be changed? I'm not too experienced with the library so I'm not sure if it's possible or if it even makes sense.

**Comment by sirskunkalot** [comment]
fixed by #19
