### ISSUE TITLE
[FEATURE] Localization Token Register per Mod

### ISSUE THREAD

**Issue by T3kla** [Valheim-Modding/Jotunn#198]
### User Story
As a {me} I want {Jotunn to track added localization tokens and the mod that added them} so that {ez token removal and localization debugging become posible}.

### Envisioned Solution
Just make **Dictionary<string, HashSet<string>> CustomTokens;**. Each time the mod adds a token, a copy of the token key is added to the list. Then add some cool methods:
- tokenClass LocalizationManager.Instance.GetTokens(string modGUID)
- bool LocalizationManager.Instance.RemoveTokens(string modGUID)
- string[] LocalizationManager.Instance.FindModsThatAddToken(string tokenKey)

In Discord was proposed that a log warning should be shown in case a mod overwrites another mod key, which would be cool.

### Additional context
Seals are water dogs

**Comment by T3kla** [comment]
Made a PR with this exact functionality. Maybe you guys need to update this issue or something? idk

**Comment by sirskunkalot** [comment]
closed with #287
