### ISSUE TITLE
[FEATURE] Add date/time when using Jotunn.Logger.Log methods

### ISSUE THREAD

**Issue by redseiko** [Valheim-Modding/Jotunn#225]
**User Story**
As a User I want to have the date/time prefixed to log statements made using Jotunn.Logger so that it matches the functionality of the standard unity logging (such as ZLog/etc) and that it is helpful for investigating and debugging.

**Envisioned Solution**
Currently Jotunn.Logger will output:
`[Info   :Jotunn.Managers.SynchronizationManager] Sending admin status to peer #641814589: Admin`

I would like this to output (or some variation or configurable):
`[05/22/2021 14:00:00] [Info   :Jotunn.Managers.SynchronizationManager] Sending admin status to peer #641814589: Admin`

**Comment by sirskunkalot** [comment]
Added in 2.0.11. Just set Jotunn.Logger.ShowDate = true in your Awake(). But beware that this is global.
