### ISSUE TITLE
Option to query / cache admin status of player again

### ISSUE THREAD

**Issue by sirskunkalot** [Valheim-Modding/Jotunn#234]
some public method which requeries ZNet.m_adminlist again and sets SyncManager,isAdmin?

**Comment by baruchvlz** [comment]
What would be the benefit of this vs doing something like `ZNet.instance.m_adminlist.Contains(SteamID)` in the mod?

**Comment by sirskunkalot** [comment]
> What would be the benefit of this vs doing something like `ZNet.instance.m_adminlist.Contains(SteamID)` in the mod?

That only works on the server side and not on the client
