### ISSUE TITLE
SynchronizationManager.Instance.PlayerIsAdmin doesn't behave as normal commands

### ISSUE THREAD

**Issue by T3kla** [Valheim-Modding/Jotunn#235]
### Facts
- **"SynchronizationManager.Instance.PlayerIsAdmin"** retrieves the original admin list once when connecting to the server, but it doesn't update later without reconnecting.
- If player is added to the admin list while the connection is active, SynchronizationManager will not know and the command that use it will fail the admin check.
- Vanilla commands do check the admin list every time and won't fail.

### Problem
If I make a command that check if player is admin with **"SynchronizationManager.Instance.PlayerIsAdmin"** this can happen: 
1. Connect to server
2. Forgot I'm not admin
3. Add myself to admin list
4. Try a Jotunn command and see it doesn't work
5. Try a vanilla command and see it does work
6. Think that Jotunn and/or my mod are broken

**Comment by sirskunkalot** [comment]
also see #234

**Comment by T3kla** [comment]
Yeah, almost the same thing posted slightly sooner.

**Comment by sirskunkalot** [comment]
Oh, yeah. Sorry, that was just for us internally cause I proposed a solution for discussion there ;) Thanks for the actual problem description.
