### ISSUE TITLE
[FEATURE] Allow skip of Icon check for monster related ItemDrops

### ISSUE THREAD

**Issue by sbtoonz** [Valheim-Modding/Jotunn#237]
**User Story**
I would love to be able to flag for skipcheck on icon check 
because ItemDrops for monsters do not need this as they should never go in player inv anyway

**Envisioned Solution**
true/false flag or similar flag to change strictness of icon check

**Additional context**
monster weapons dont have icons as they are never meant to be crafted for player

**Comment by sirskunkalot** [comment]
Just demand an icon when certain conditions are met (so it is clearly an item which can be build/picked up by the payer). Extend that check in the ItemDrop extension.

**Comment by sirskunkalot** [comment]
fixed in 2.1
