### ISSUE TITLE
RecipeConfig.cs (line105): RepairStation not being assigned (CraftingStation assigned twice)

### ISSUE THREAD

**Issue by qt31415926535-femboy** [Valheim-Modding/Jotunn#249]
[https://github.com/Valheim-Modding/Jotunn/blob/498cb31872d018597f56b7b75e93e540cd06983f/JotunnLib/Configs/RecipeConfig.cs/#L37](https://github.com/Valheim-Modding/Jotunn/blob/498cb31872d018597f56b7b75e93e540cd06983f/JotunnLib/Configs/RecipeConfig.cs/#L37)

lines 98 through 106:
```csharp
if (!string.IsNullOrEmpty(CraftingStation))
{
    recipe.m_craftingStation = Mock<CraftingStation>.Create(CraftingStation);
}

if (!string.IsNullOrEmpty(RepairStation))
{
    recipe.m_craftingStation = Mock<CraftingStation>.Create(RepairStation);
}
```

**recipe.m_repairStation** should be the value modified in line 105 rather than **recipe.m_craftingStation**

**Comment by Algorithman** [comment]
Nice find, fixed in a few. Thx
