### ISSUE TITLE
NetworkCompatibility

### ISSUE THREAD

**Issue by paddywaan** [Valheim-Modding/Jotunn#25]
A NetworkCompatibilityModule for plugin developers to "enforce" synchronisation between client's mods/versions, and potentially configs.

See: https://github.com/risk-of-thunder/R2API/blob/master/R2API/Utils/NetworkCompatibility.cs

* Must ensure plugins can request clients to have a certain dependency
* Must ensure plugins can request clients to have a certain version of that dependency
* Must ensure plugins can be permissive with versioning
* Must ensure synchronisation of specific configurations / bep whole configurations
* Does **NOT** attempt to act as an anti-cheat.
* Clients failing to meet conditions must be notified of the offending/lacking dependencies if/when connection is refused.

Potentially utilise/suggest https://github.com/BepInEx/BepInEx.ConfigurationManager for UI frontend for configs

**Comment by sirskunkalot** [comment]
Just for the sake of discussion I will restate and relink that a complete config system (including valheim look&feel GUI and sync and admin rights) is already available at our mod and could be merged into the lib quite easy: https://github.com/sirskunkalot/Veilheim#configuration-gui-and-sync
