### ISSUE TITLE
Im getting this error in Bepinex

### ISSUE THREAD

**Issue by AJ1Stone** [Valheim-Modding/Jotunn#251]
Message:WindSeeker.WindSeeker] Loaded Game VFX and SFX
[Error :Jotunn.EventExtensions] System.MissingFieldException: Field 'StaticTarget.m_center' not found.
at Jotunn.EventExtensions.SafeInvoke (System.Action events) [0x00018] in <87f5edfa58dd4ccba75b4848c29c2905>:0

**Comment by sbtoonz** [comment]
uhm

windlass doesnt touch this field

old versions of moar builds did 

you need to update your moar builds

**Comment by sbtoonz** [comment]
;)

**Comment by sirskunkalot** [comment]
sbtoonz is right, thats a mod using Jötunn, not the lib itself. The game update broke some mods and the respective owners have to update accordingly.

**Comment by AJ1Stone** [comment]
I do not have Moar Builds installed. 
I had Steam Uninstall and Re install Valheim, I added all my mods back in MINUS Moar Builds (even took out the config file)
Upon rebooting the game, I still get this error, so Its not Moar Builds.

**Comment by sirskunkalot** [comment]
It is not necessarily MoarBuilds. could be any Jötunn mod that was not updated.

**Comment by AJ1Stone** [comment]
It was actually CustomBuildingItems because the dev failed to put a Json file in the newest (April) download file.
So I went to the previous download and grabbed it, and now it is running just fine, no more red errors.
It was this mod.
https://valheim.thunderstore.io/package/Smallo/CustomBuildingItems/
