### ISSUE TITLE
Include vanilla item tokens in JotunnDoc

### ISSUE THREAD

**Issue by sirskunkalot** [Valheim-Modding/Jotunn#254]

**Comment by baruchvlz** [comment]
By tokens, do you mean the [ObjectDB](https://www.nexusmods.com/valheim/articles/65) names?

**Comment by sirskunkalot** [comment]
Nope, I mean the translation tokens in m_shared. Actually I already implemented that in v2.1.3 and forgot to close the issue...

See https://valheim-modding.github.io/Jotunn/data/objects/item-list.html for example

The item names were already in there before...

**Comment by sirskunkalot** [comment]
fixed in v2.1.3
