### ISSUE TITLE
dll sure, but the others?

### ISSUE THREAD

**Issue by MrKrumb** [Valheim-Modding/Jotunn#257]
Sorry for being a newb.. Minor issue - documentation says to drop .dll in plugins folders. So what about the .pdb and .xml?!
Sure I'd like to use Vortex but for some reason it doesn't work with an existing bepinex install, which is just silly. Thanks for your  time!

**Comment by sirskunkalot** [comment]
These are used for developing and debugging. For Jötunn to run in the game the .dll is sufficient.
