### ISSUE TITLE
Deconflict Custom Key Bindings

### ISSUE THREAD

**Issue by jcleveland** [Valheim-Modding/Jotunn#30]
As more mods need custom key bindings it would be nice to have a common approach to coordinating / de-conflicting bindings. There are a few different ways I could see this working ranging in technical complexity from agreed upon standards although way to common code library for managing key bindings.  While some of the less technical approaches may not need Jotunn library support for them it seems this wiki would still be a good place to document them. 

I'm throwing some possible options below, likely some combination of them will end up making sense. I'm sure there may be other solutions that would work even better. 

Option 1:
Mods standardize on using a **ModKeyBinding** section in BepinEx.Configuration. This would allow the user to easily see all of the custom key bindings they need to setup.

Option 2:
For common custom button bindings Jotunn sets up the key binding for them. An example of this would be several mods may want a **Use2** binding. Jotunn's config could define the **Use2** key binding so that mods wouldn't have to manage the configuration themselves. For something like Use2 we could also have an agreed upon interface where a method **Interact2** gets called on the object being used. 

Option 3:
Jotunn provides mechanism for mods to register key bindings needed and they get added to the actual Valheim configuration screen as opposed to just a BepinEx configuration file.

**Comment by paddywaan** [comment]
Perhaps we should implement keybinds underneath https://github.com/BepInEx/BepInEx.ConfigurationManager to further utilisation of native libraries and provide a more standardised interface for configurations.

**Comment by Algorithman** [comment]
Option 3 is pretty much locked in.

- But how to resolve this: Fresh installation of mods, they got their default values for the Use2 binding.
I can collapse the 2 Keybinding entries in the settings menu to one, but which KeyCode to show? (Same if someone changes it in the config file and then restarts)
First come first serve?
- How to display them? 
Make a separate section for these keybindings and display 'Used by mod1, mod2'? Or leave them in their respective Mod sections and change both if you change any of them? The latter might confuse people imo.

Internally there won't be any changes, AddButton will still need the modGuid parameter, but the configuration screen will keep them sync'd.
