### ISSUE TITLE
missingmethodexception

### ISSUE THREAD

**Issue by DrTim93** [Valheim-Modding/Jotunn#304]
i get this for some reasone "[Error  : Unity Log] MissingMethodException: UnityEngine.GameObject[] EffectList.Create(UnityEngine.Vector3,UnityEngine.Quaternion,UnityEngine.Transform,single)
Stack trace:
(wrapper dynamic-method) Player.DMD<Player::Update>(Player) "

**Comment by sirskunkalot** [comment]
Sorry, that is not really helpful. Please use the bug report template and provide the needed information.
