### ISSUE TITLE
[DOCS] Creature Prefab List in Valheim Data

### ISSUE THREAD

**Issue by koosemose** [Valheim-Modding/Jotunn#308]
If it's possible to do in an automated fashion, it could be useful to have a list exclusively of creature Prefabs in the Valheim Data section along with their in game name, as it is a few extra steps to dig through the project to find the appropriate names, particularly for creatures such as the Drake/Hatchling, that have very different prefab names from their in game name.

**Comment by joeyparrish** [comment]
This sounds very doable.  I could use this, too, as it's the most common thing I search the prefab list for.  I volunteer as tribute!

**Comment by joeyparrish** [comment]
@koosemose, here's a preview: https://joeyparrish.github.io/Jotunn/data/prefabs/character-list.html

Is this helpful?
