### ISSUE TITLE
switching from local game based bepinex to nuget dependencies

### ISSUE THREAD

**Issue by sirskunkalot** [Valheim-Modding/Jotunn#326]
its all there - https://nuget.bepinex.dev
publicized game assemblies would be, too, but creating own versions on the fly is more flexible.

**Comment by MSchmoecker** [comment]
Closing this. Using local assemblies is usually more reliable, even for BepInEx. A dev environment for starting Valheim with mods is needed anyway.

The `Environment.props` can be used to overwrite paths. Default values are used for `VALHEIM_INSTALL`/`BEPINEX_PATH` and only need to be set if the setup isn't ordinary:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="Current" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <VALHEIM_INSTALL>X:\PathToYourSteamLibary\steamapps\common\Valheim</VALHEIM_INSTALL>
    <BEPINEX_PATH>$(VALHEIM_INSTALL)\BepInEx</BEPINEX_PATH>
  </PropertyGroup>
</Project>
```

`VALHEIM_INSTALL` and `BEPINEX_PATH` can be set independently, so even mod managers are easily supported:
```xml
<DEPLOY_FOLDER>$(AppData)\r2modmanPlus-local\Valheim\profiles\Develop</DEPLOY_FOLDER>
```
