### ISSUE TITLE
[FEATURE] Configure custom key bindings via in-game settings

### ISSUE THREAD

**Issue by joeyparrish** [Valheim-Modding/Jotunn#330]
**User Story**
As a developer, I want to enable users to customize my mod's key bindings using the in-game settings menu so that they do not have to edit config files.

**Envisioned Solution**
I'd like to be able to modify this dialog to include mod-specific key bindings:
![valheim-settings](https://user-images.githubusercontent.com/6843156/141594363-85c70849-e34c-424b-b7fc-765415cf1e7a.png)

Looking at the decompiled source of Valheim, it doesn't look especially easy.  :-/

The `Settings` class has a list called `m_keys`, but each item has a hard-coded RectTransform with a button.  I would guess that those might need to be moved and/or the dialog expanded to make room for any new settings.

Alternate solution: Would it be possible to add another tab to the settings dialog, and put mod-specific configs there?

**Comment by sirskunkalot** [comment]
Hey,

if you click on this:
![grafik](https://user-images.githubusercontent.com/14891268/141596313-0512a4c6-0914-47b2-b27c-48033832b8f6.png)

you will notice it's all in there already, including key binds ;)
![grafik](https://user-images.githubusercontent.com/14891268/141596388-faab0208-3a77-44c8-a750-fe74a1ca433c.png)

**Comment by sirskunkalot** [comment]
If you don't see your mod in there (or no mod settings at all), you probably did not use the default Config member of BaseUnityPlugin to create your config file.

**Comment by sirskunkalot** [comment]
PS: If you did not use the default Config member, you really should do that. It comes with even more perks: https://valheim-modding.github.io/Jotunn/tutorials/config.html

**Comment by sirskunkalot** [comment]
PPS: If you just don't see your key in the mod settings, you probably did not define a ButtonConfig for it and added that to the InputManager: https://valheim-modding.github.io/Jotunn/tutorials/inputs.html

**Comment by joeyparrish** [comment]
Okay, thanks.  That's very helpful.
