### ISSUE TITLE
[FEATURE] Documentation for Languages

### ISSUE THREAD

**Issue by joeyparrish** [Valheim-Modding/Jotunn#332]
**User Story**
As a developer I want to translate my mod so that it can be available in multiple languages.  However, it was unclear to me from Jotunn's localization tutorial exactly what to name the language folders.

For example, I named a folder "Deutsch", when it turns out it should have been named "German".  And had I been translating into Portuguese (hypothetical - I don't speak Portuguese), I never would have guessed the exact folder names "Portuguese_European" and "Portuguese_Brazilian" without looking it up somewhere.

**Envisioned Solution**
I want to modify JotunnDoc to generate documentation indicating which languages are supported in-game by default and what to name the folders for translations.

**Additional context**
I managed to dump the language names in a temporary patch in my mod already, so I expect I'll be able to add this to JotunnDoc and send a PR.

**Comment by joeyparrish** [comment]
I would also like to contribute an extension to this to dump all the translation tokens and their text in each language.  (Each language in its own generated MD table.)  I'm still testing it, but it will likely be done in the next day or two.  Would you prefer me to add that to this PR, or to create a follow-up PR after this?

**Comment by joeyparrish** [comment]
The translation token dump is working now, too.  See https://github.com/joeyparrish/Jotunn/commit/0f7e772e0d347e8f3c86fa2f30a6e28e1a1302b1 for the implementation, and my fork's gh-pages for the [language list](https://joeyparrish.github.io/Jotunn/data/localization/language-list.html), [English tokens](https://joeyparrish.github.io/Jotunn/data/localization/translations/English.html), and [German tokens](https://joeyparrish.github.io/Jotunn/data/localization/translations/German.html) for examples of how it will look in the final HTML output.  Happy to roll that into this PR, or send it separately.  Not sure how you prefer to do things.  (At work, we're picky about splitting up reviews, so I'm in the habit.)

**Comment by sirskunkalot** [comment]
Hey Joey,

thanks again, That's a very valuable addition to the docs. I am totally fine with adding it to this PR, too. It's our free time project, so we won't be more strict than we have to ;)

**Comment by joeyparrish** [comment]
Cool.  I'll update the PR.
