### ISSUE TITLE
JvL ModStub for TMM/R2ModMan

### ISSUE THREAD

**Issue by FelixReuthlinger** [Valheim-Modding/Jotunn#339]
**User Story**
As a developer I would like to be able to also use TMM (or R2) for the mod stub. 

**Envisioned Solution**
It would be helpful if the Environment.props had an option to also provide the profile(s) path there, so it could pull BepInEx from there and publish the dll also back to the profile. Using TMM / R2 you could easily have 1 profile for each mod you develop and would not need to cleanup your vanilla Valheim installation if developing multiple mods.

**Comment by sirskunkalot** [comment]
Yes, this is something I thought about before, too. Will implement that soon.

**Comment by sirskunkalot** [comment]
Implemented in the current version of the mod stub project. You will have to update your Environment.props, publish.ps1 and .csproj file, though...
