### ISSUE TITLE
Workflows are referencing vulnerable actions

### ISSUE THREAD

**Issue by igibek** [Valheim-Modding/Jotunn#346]
Hello, there! 

As part of the university research we are currently doing regarding the security of Github Actions, we noticed that one or many of the workflows that are part of this repository are referencing vulnerable versions of the third-party actions. As part of a disclosure process, we decided to open issues to notify GitHub Community. 

*Please note that there are could be some false positives in our methodology, thus not all of the open issues could be valid. If that is the case, please let us know, so that we can improve on our approach. You can contact me directly using an email: ikoishy [at] ncsu.edu* 

Thanks in advance
1. The workflow **merge.yml** is referencing action **gittools/actions/gitversion/setup** using references **v0.9.7**. However this reference is missing the commit [90150b4](https://github.com/gittools/actions/commits/90150b4) which may contain fix to the vulnerability.
1. The workflow **merge.yml** is referencing action **gittools/actions/gitversion/execute** using references **v0.9.7**. However this reference is missing the commit [90150b4](https://github.com/gittools/actions/commits/90150b4) which may contain fix to the vulnerability.
1. The workflow **pull-request.yml** is referencing action **gittools/actions/gitversion/setup** using references **v0.9.7**. However this reference is missing the commit [90150b4](https://github.com/gittools/actions/commits/90150b4) which may contain fix to the vulnerability.
1. The workflow **pull-request.yml** is referencing action **gittools/actions/gitversion/execute** using references **v0.9.7**. However this reference is missing the commit [90150b4](https://github.com/gittools/actions/commits/90150b4) which may contain fix to the vulnerability.

The vulnerability fix that is missing by actions' versions could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider updating the reference to the action. 

*If you end up updating the reference, please let us know. We need the stats for the paper :-)*

**Comment by xiaoxiao921** [comment]
For this to be remotely useful would be giving the vulnerability nature. In its current state it's worse than the current reports you get from npm cli. Also in the case of a redos vuln it doesn't make much sense to report it to us. If anything it's a problem for GitHub to even allow such version to be used on their servers

**Comment by MSchmoecker** [comment]
Fixed by updating gittools/actions/gitversion/setup and gittools/actions/gitversion/execute to v0.10.2
