### ISSUE TITLE
[BUG] plugin completely breaks game as of patch 0.207.15

### ISSUE THREAD

**Issue by TheF00Man** [Valheim-Modding/Jotunn#350]
Details: Currently the Valheim beta release for 0.207.15
Jotunn Version: 2.5.1
Jotunn Submodule(if applicable):
Repeatability(Consistent(100%), Inconsistent(50%), Rare(1%), Unknown(==1)): 100%

**Problem Description:**
Starting game menu does not render correctly with plugin installed. Cannot switch between characters and the view does not change at all tried.  Actually scared to attempt to launch a game file. 

**Expected Behaviour:**
Start menu and character select to work and not have incorrect information.

**Actual Behaviour:**
Looks like the plugin is exposing string variables to the starting menu. 
[Log.TXT](https://github.com/Valheim-Modding/Jotunn/files/8092262/Log.TXT)

**Link to your server's and client's LogOutput.log**
Attach a sample log file at this just spams out heck out of the log window.

**Comment by sirskunkalot** [comment]
Current dev version of Jötunn is already compatible with the beta. You can build it yourself against the public test or use this binary:
[Jotunn-2.5.1-publictest.zip](https://github.com/Valheim-Modding/Jotunn/files/8092732/Jotunn-2.5.1-publictest.zip)

**Comment by TheF00Man** [comment]
Thank you very much, doing some testing now.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by sirskunkalot** [comment]
Closing this with the hint to the build actions of this repo which compile against the current test release on push. You can grab binaries there until the game patch is final and released.
