### ISSUE TITLE
[BUG] With the `Fight Club` mod installed, Valheim starts with errors

### ISSUE THREAD

**Issue by rakleed** [Valheim-Modding/Jotunn#353]
Details: https://www.nexusmods.com/valheim/mods/223?tab=bugs
Jotunn Version: 2.6.0
Jotunn Submodule(if applicable): Jotunn.Managers.InputManager
Repeatability(Consistent(100%), Inconsistent(50%), Rare(1%), Unknown(==1)): Consistent (100%)

**Problem Description:**
With the [Fight Club](https://www.nexusmods.com/valheim/mods/223) mod installed, Valheim starts with errors and does not work normally. With the Fight Club mod installed, the game starts with errors and does not work normally. The author of the Fight Club mod ?celz in the logs indicates a problem with `Jotunn.Managers.InputManager.RegisterCustomInputs`.

**Expected Behaviour:**
The mod starts and works correctly.

**Actual Behaviour:**
The mod does not run due to an error with `Jotunn.Managers.InputManager.RegisterCustomInputs`.

**Link to your server's and client's LogOutput.log**
```
[Error  : Unity Log] MissingMethodException: ZInput/ButtonDef ZInput.AddButton(string,UnityEngine.KeyCode,single,single)
Stack trace:
(wrapper dynamic-method) ZInput.DMD<ZInput::Load>(ZInput)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<ZInput::Load>?2004023296(ZInput)
Jotunn.Managers.InputManager.RegisterCustomInputs (On.ZInput+orig_Load orig, ZInput self) (at <52612d9b2278460c81b3b16689632cb8>:0)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<ZInput::Load>?-913914112(ZInput)
ZInput..ctor () (at <e2ad8b24c5224f5a8365347f64597ff3>:0)
ZInput.Initialize () (at <e2ad8b24c5224f5a8365347f64597ff3>:0)
(wrapper dynamic-method) FejdStartup.DMD<FejdStartup::Start>(FejdStartup)
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
FejdStartup.UpdateCursor () (at <dcb0de0155834d459f18d7ac6ea5244b>:0)
FejdStartup.Update () (at <dcb0de0155834d459f18d7ac6ea5244b>:0)
```

**Comment by MSchmoecker** [comment]
The error also occurs when Jotunn is not installed. This is a problem with Fight Club itself
```
[Error  : Unity Log] MissingMethodException: ZInput/ButtonDef ZInput.AddButton(string,UnityEngine.KeyCode,single,single)
Stack trace:
(wrapper dynamic-method) ZInput.DMD<ZInput::Load>(ZInput)
ZInput..ctor () (at <e2ad8b24c5224f5a8365347f64597ff3>:0)
ZInput.Initialize () (at <e2ad8b24c5224f5a8365347f64597ff3>:0)
(wrapper dynamic-method) FejdStartup.DMD<FejdStartup::Start>(FejdStartup)
```
