### ISSUE TITLE
Singleton pattern implemented via MonoBehaviour's prevents unit testing abstractions

### ISSUE THREAD

**Issue by paddywaan** [Valheim-Modding/Jotunn#36]
As mentioned: https://github.com/Valheim-Modding/Jotunn/pull/32#issuecomment-813017472 we would need to remove this inheritance, and instead use interfaces in order to implement unit testing. Similarly if we really want to go down this route we should look into the Dependency Injection design pattern and integrate it into all managers so that we can pass our collections as dependencies via constructor, param, or method. 

This would mean rewriting how we invoke our managers, however it should allow us to be more consistent in code quality.

**Comment by sirskunkalot** [comment]
Vote to add this to V1.1 so its not in the way of the release of V1.0
