### ISSUE TITLE
[BUG] Can't mock against the meshes default_441 or default_445

### ISSUE THREAD

**Issue by GravenImageRD** [Valheim-Modding/Jotunn#361]
Details:
Jotunn Version: 2.6.3
Jotunn Submodule(if applicable):
Repeatability(Consistent(100%), Inconsistent(50%), Rare(1%), Unknown(==1)): Consistent

Problem Description:
I have been using mocking in a mod I'm working on but attempts to mock the Ruby prefab so I can use the mesh default_441 (mocked as JVLmock_default_441) fails because it is unable to mock it. I've verified the behavior with default_445 as well, and swapped in a mock I know worked (a JVLmock_amber mesh) and the mocking worked as expected. It's something to do with those default_ meshes, not sure if it is all of them though or just some?

Expected Behaviour:
Be able to mock against default_441 so I can use the ruby mesh.

Actual Behaviour:
Error is thrown that it can't instantiate the default_441 mock.

Link to your server's and client's LogOutput.log
Upload to https://pastebin.com/ or simliar service

**Comment by MSchmoecker** [comment]
As far as I know this is not possible because the real mesh name isn't default_441 but only default. The number is only given by the decompiler not how it is named inside the project. This means there is sadly no unique name from what the mesh could be received.

**Comment by GravenImageRD** [comment]
Oof, that's a bummer but makes sense.

**Comment by sirskunkalot** [comment]
You could probably get the needed prefab in code and clone its mesh to use in your own prefab. It's not that convenient, but should work. I am closing the issue though, since there is not much we can do about it.
