### ISSUE TITLE
Option to hide Mod Settings (or make it work for all mods)

### ISSUE THREAD

**Issue by literallygoblin** [Valheim-Modding/Jotunn#368]
A lot of interesting mods depend on Jotunn, but a lot more don't, and they all need to be configured.

Not everyone wants their UI messed with, or require the option to configure the mods in-game at all.
That becomes doubly true for a function that potentially does not get used because it only works for a fraction of the mods in a load order, all of which can all be configured where you have to go to configure the remaining mods anyway.

I simply propose the option to hide the Mod Settings UI.

Either that, or making it work for all the mods in a load order so that it serves a purpose not already covered elsewhere.

**Comment by sirskunkalot** [comment]
New Jötunn version will have both: A config option to disable Mod settings and will also show all mod configs, not just Jötunn ones.
