### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by dwdbmeagle** [Valheim-Modding/Jotunn#378]
Details:
Jotunn Version:2.9.0 (server and client)
Jotunn Submodule(if applicable):
Repeatability(Consistent(100%), Inconsistent(50%), Rare(1%), Unknown(==1)): 

**Problem Description:**
Using a linux client connecting to a modded valheim server using Jotunn like Reloaded or if I setup a local server on my lan using Jotunn (linux client and server), Jotun results in a client disconnection error.

**Expected Behaviour:**
Client should not be disconnected

**Actual Behaviour:**
Client is disconnected

**Link to your server's and client's LogOutput.log**
Upload to https://pastebin.com or simliar service
[Player.log](https://github.com/Valheim-Modding/Jotunn/files/10046970/Player.log)

[Debug  :Jotunn.Managers.LocalizationManager] Added translation: mod_compat_header_failed_connection -> Failed Connection:
[Debug  :Jotunn.Managers.LocalizationManager] Added translation: mod_compat_header_remote_version -> Remote Version (the Server):
[Debug  :Jotunn.Managers.LocalizationManager] Added translation: mod_compat_header_local_version -> Local Version (this Game):
[Debug  :Jotunn.Managers.LocalizationManager] Added translation: mod_compat_header_valheim_version -> Valheim Version Error:
[Debug  :Jotunn.Managers.LocalizationManager] Added translation: mod_compat_header_version_string -> Valheim Modded Version String Mismatch:
[Debug  :Jotunn.Managers.LocalizationManager] Added translation: mod_compat_header_missing_mods -> Missing Mods:
[Debug  :Jotunn.Managers.LocalizationManager] Added translation: mod_compat_header_update_needed -> Mod Updates Needed:
[Debug  :Jotunn.Managers.LocalizationManager] Added translation: mod_compat_header_downgrade_needed -> Mod Downgrades Needed:
[Debug  :Jotunn.Managers.LocalizationManager] Added translation: mod_compat_header_additional_mods -> Additional Mods Loaded:
[Debug  :Jotunn.Managers.LocalizationManager] Added translation: mod_compat_valheim_version_error_description -> The server runs Valheim $1, while your game runs Valheim $2
[Debug  :Jotunn.Managers.LocalizationManager] Added translation: mod_compat_valheim_version_upgrade -> Please update your game to Valheim $1 or contact your server admin

**Comment by MSchmoecker** [comment]
This log doesn't tell much, please send your server log (from `BepInEx/LogOutput.log`), too.
Since you have other mods installed, it's more likely one of them is responsible for the disconnect. There was an update some time ago that broke ServerSync, but without the server log this is hard to tell.

The log snippet you send only shows possible translation that were added for the UI, but not that Jotunn had disconnected the client.

**Comment by dwdbmeagle** [comment]
[LogOutput.log](https://github.com/Valheim-Modding/Jotunn/files/10047123/LogOutput.log)
Here is the log as requested, I shortened it, the last set of stack trace errors just repeat for many megabytes:
"[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ZInput.IsGamepadActive () (at <54bcee0561504e93a88e7eac2654f4dd>:0)
UIGroupHandler.Update () (at <408fb2feebfa4a519b8eeaef491b5d76>:0)"

**Comment by MSchmoecker** [comment]
The first error for this is this:
```
[Error  : Unity Log] FormatException: Input string was not in a correct format.
Stack trace:
System.Number.StringToNumber (System.String str, System.Globalization.NumberStyles options, System.Number+NumberBuffer& number, System.Globalization.NumberFormatInfo info, System.Boolean parseDecimal) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Number.ParseInt32 (System.String s, System.Globalization.NumberStyles style, System.Globalization.NumberFormatInfo info) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Int32.Parse (System.String s) (at <695d1cc93cca45069c528c15c9fdd749>:0)
(wrapper dynamic-method) FejdStartup.DMD<FejdStartup::ParseServerArguments>(FejdStartup)
(wrapper dynamic-method) FejdStartup.DMD<FejdStartup::Awake>(FejdStartup)
```

It seems you have set an invalid port in your server start arguments, only numbers are valid. That error likely causes the issues afterwards.
Please send your new log again if you still cannot log in and the port is fixed.

**Comment by dwdbmeagle** [comment]
Thank you very much for the feedback, problem is now solved, the server startup parameters were not correct, the lgsm startup parameter variable names were the problem.
