### ISSUE TITLE
[BUG] Docs - Helmets and swords in Vegetation list

### ISSUE THREAD

**Issue by luxzg** [Valheim-Modding/Jotunn#384]
Details:  Items placed in wrong category
Jotunn Version: latest
Jotunn Submodule(if applicable): doc generator
Repeatability(Consistent(100%), Inconsistent(50%), Rare(1%), Unknown(==1)): current

**Problem Description:**
Looking at "https://valheim-modding.github.io/Jotunn/data/zones/vegetation-list.html" that uses Jotunn Docs modules items like:

- giant_helmet1
- giant_helmet2
- giant_sword1
- giant_sword2

are in the Vegetation

**Expected Behaviour:**
Should be in Locations list together with:

- Mistlands_Swords1
- Mistlands_Swords2
- Mistlands_Swords3

**Actual Behaviour:**
What actually occurs

**Link to your server's and client's LogOutput.log**
Upload to https://pastebin.com or simliar service

**Comment by sirskunkalot** [comment]
It's actually how the devs implemented it. There are locations *and* vegetation for those swords and giants. The locations you listed as examples are in the location list. Just double checked in the rip.
