### ISSUE TITLE
[BUG] Incompatobility with Valheim 0.214.300

### ISSUE THREAD

**Issue by JackTheFragger** [Valheim-Modding/Jotunn#392]
Details:
Valheim: 0.214.300
BepInEx: 5.4.21.0
Jotunn Version: 2.11.2
Jotunn Submodule(if applicable):
Repeatability(Consistent(100%), Inconsistent(50%), Rare(1%), Unknown(==1)): Consistent

**Problem Description:**
Dedicated server doesn't startup with Jotunn installed.

**Expected Behaviour:**
No error at startup. Server starts up. 

**Actual Behaviour:**
[Error  : Unity Log] NullReferenceException
Stack trace:
UnityEngine.Object.get_name () (at <80fe1a4e36fe44618284312cb721a597>:0)
Jotunn.Entities.CustomItem.ToString () (at D:/Projects/Jotunn/JotunnLib/Entities/CustomItem.cs:211)
System.Text.StringBuilder.AppendFormatHelper (System.IFormatProvider provider, System.String format, System.ParamsArray args) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.String.FormatHelper (System.IFormatProvider provider, System.String format, System.ParamsArray args) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.String.Format (System.String format, System.Object arg0, System.Object arg1) (at <695d1cc93cca45069c528c15c9fdd749>:0)
Jotunn.Managers.ItemManager.RegisterCustomItems (ObjectDB objectDB) (at D:/Projects/Jotunn/JotunnLib/Managers/ItemManager.cs:398)
Jotunn.Managers.ItemManager.RegisterCustomDataFejd (ObjectDB self, ObjectDB other) (at D:/Projects/Jotunn/JotunnLib/Managers/ItemManager.cs:686)
Jotunn.Managers.ItemManager+Patches.RegisterCustomDataFejd (ObjectDB __instance, ObjectDB other) (at D:/Projects/Jotunn/JotunnLib/Managers/ItemManager.cs:77)
(wrapper dynamic-method) ObjectDB.DMD<ObjectDB::CopyOtherDB>(ObjectDB,ObjectDB)
(wrapper dynamic-method) FejdStartup.DMD<FejdStartup::SetupObjectDB>(FejdStartup)
(wrapper dynamic-method) FejdStartup.DMD<FejdStartup::Start>(FejdStartup) 

**Link to your server's and client's LogOutput.log**
Upload to https://pastebin.com or simliar service

**Comment by MSchmoecker** [comment]
This likely means BepInEx is not up to date, make sure to download the latest version from here https://valheim.thunderstore.io/package/denikson/BepInExPack_Valheim/. More specifically, this error is caused by an old BepInEx.cfg inside BepInEx/config folder. The entrypoint changed with the latest Valheim release.

**Comment by JackTheFragger** [comment]
Thanks. BepInEx is up to date, but config were not renewed by docker container lloesche/valheim. I've did it manually. Server runs fine now.
