### ISSUE TITLE
[BUG] Particle System not working under Linux (alpha blended shaders)

### ISSUE THREAD

**Issue by bidsoft** [Valheim-Modding/Jotunn#395]
First, I want to thank you for providing this great library!!!

I am having issues with the particle systems under Linux; everything works fine under Windows (well, besides the OS itself ;))
The issue seems to arise from shaders when setting them to alpha blend. I tried all possible shaders with two results:
- for most of the shaders the texture is just pink
- for some shaders the texture is applied in a very strange way

You can reproduce it with running your mod example on Linux - it does not work there either.

In the meantime I am mocking one of the in-game particle systems - these work flawlessly.

Hope you can help.
Thx

**Comment by MSchmoecker** [comment]
This is a Vulkan rendering issue, your Unity project where you build your AssetBundles must be setup to support it.

Go to Project Settings > Player > Other Settings > uncheck Auto Graphics API for Windows and Linux respectively and add Vulkan to the drop down.

**Comment by bidsoft** [comment]
Thx for your fast response, but it did not change anything.
What I did: unchecked Windows and Linux Auto Graphics API. For Linux there was already Vulkan in the list, but moved it above OpenGL.
Tested with the following shader: Legacy Shaders -> Particles -> Alpha Blend
Am I missing something else?

It seems do be some kind of common issue, as I have seen people in the community complaining that mods (textures) are not working correctly on Linux, but I do not know if these mods use JVL.

**Comment by MSchmoecker** [comment]
Closing because this is related to Unity, not Jotunn itself

**Comment by justinko** [comment]
@bidsoft can I pay you for your username? my email is on my profile

**Comment by bid-soft** [comment]
@justinko no sorry
