### ISSUE TITLE
[BUG] Cannot build with this mod library installed

### ISSUE THREAD

**Issue by Garek56** [Valheim-Modding/Jotunn#406]
Details:
Jotunn Version: 2.12.4
Repeatability Consistent 100%

**Problem Description:**
I cannot place any build items when this is running, and i've tried with only this and bepinex, and nothing else.

**Expected Behaviour:**
i can place buildings or use my hoe

**Actual Behaviour:**
i can't place buildings or terraform

https://pastebin.com/2pmZjqdj
unfortunately there's just a huge stream of errors that i can't really decipher, and i apologize for that... the game was only running for like a minute and all of that is already in the log...

**Comment by MSchmoecker** [comment]
The error in the log is because of the PrecisePiecePlacement mod, which doesn't seem to have been updated for the current Valheim release. As it depends on Jotunn, it will only load if Jotunn is also installed.
