### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by huntzilla360c** [Valheim-Modding/Jotunn#428]
![Screenshot (1)](https://github.com/SpikeHimself/XPortal/assets/61102631/cc9fd785-74c4-4c0d-ad6e-668736bd970e)

![20240426173625_1](https://github.com/SpikeHimself/XPortal/assets/61102631/571f9de3-ee2e-4695-92bb-6e7eba838953)

![20240426173632_1](https://github.com/SpikeHimself/XPortal/assets/61102631/7151a914-fa7f-431f-8200-643c456ce1fd)
.
.
.
I'm having this issue, I've updated every single mod I could, and there are no conflicts with any other mod but I'm seeing GUI issues with Jotun in the console. Jotun is installed but I don't think correctly, as I had all the Jotun files just sitting in my plugins folder on my old PC where Xportal **WAS** working, but I looked on the ThunderStore and it says to just drop the Xportal and the Jotun folders into the Plugins folder
.
.
.
![Screenshot 2024-04-26 174725](https://github.com/SpikeHimself/XPortal/assets/61102631/bfbf0282-3625-46e3-86f4-9bc7ef55c28c)
.
.
For reference, I **DID** have both folders emptied into the plugins folder before these screenshots, but it wasn't working then either
.
.
.
**Describe the bug**
When I attempt to use the portal, I am met with the Vanilla portal UI and cannot select other portals as a destination. ALSO cannot see Ore Support elements from the mod Ore_Support, ALSO signs do not appear correctly, they only have "**...**" any text will produce that
.
.
**To Reproduce**
both on my, my brothers, and my friends' clients. 
.
.
**Environment**
 Multiplayer Host
 Multiplayer Client    (ALL)
 Singleplayer
.
.
**Other mods**
I've isolated to only Bepin(5.4.22.0), Jotun (2.19.3), and Xportal (1.2.20) in the plugins folder, then deleted all the configs(which shouldn't affect if it doesn't have DLLs) and it still wouldn't work.
You'll see the other mods I normally play within the pictures.
.
.
Details:
Jotunn Version:  2.19.3
Jotunn Submodule(if applicable): 
Repeatability(Consistent(100%)
.
.
**Problem Description:**
I did post this to Xportals but I copied the entire contents into this report and I think it is an issue with the GUIManager from Jotun
.
.
**Expected Behaviour:**
GUI/elements to appear. 
.
.
**Actual Behaviour:**
GUI's not appearing, and other elements are not appearing correctly
.
.
**Link to your server's and client's LogOutput.log**
[LogOutput.log](https://github.com/SpikeHimself/XPortal/files/15135635/LogOutput.log)

**Comment by huntzilla360c** [comment]
https://github.com/SpikeHimself/XPortal/issues/98

**Comment by huntzilla360c** [comment]
Spike said it wasnt Jotun, so ill close this end

**Comment by MSchmoecker** [comment]
It looks like a different BepInEx pack than https://thunderstore.io/c/valheim/p/denikson/BepInExPack_Valheim/ was installed, or the BepInEx install is broken. Please reinstall the mods with the pack above, any other may not work as expected. Maybe reinstall the full game too, just to be sure

**Comment by huntzilla360c** [comment]
THAT WAS IT!!! thank you so much, and I'm sorry for the wild goose chase, thank you. https://github.com/BepInEx/BepInEx/releases   this is where I got it
