### ISSUE TITLE
Network compatibility more precise controls

### ISSUE THREAD

**Issue by raduschirliu** [Valheim-Modding/Jotunn#50]
Perhaps it would be worth it to add some more precise controls for the `NetworkCompatibility.VersionStrictness` enum. It may be useful to allow something along the lines of:
- Versions do not matter
- Everyone needs same `major` version, minor.patch does not matter
- Everyone needs same `major.minor` version, patch does not matter
- Everyone needs same mod version for `major.minor.patch`

**Comment by paddywaan** [comment]
Yeah this could be a decent addition to be honest with you. Nothing against this.
