### ISSUE TITLE
[FEATURE] Prefab naming consistency and persistance

### ISSUE THREAD

**Issue by Igmat** [Valheim-Modding/Jotunn#53]
### User Story
As a **Mod developer** I want to be able to refactor my code related to prefabs so that prefabs have unchanged identity unless I explicitly decided them to do so.

As a **Player** I want to have my custom items/pieces persist in world even after updating mod so that I'm able to take latest version of mods without losing progress in my saved world.

### Envisioned Solution
Using `InstantiateClone` (or similar method) shouldn't alter name provided by developer in a way that prevents developer from any further changes around calling this method. Like it currently does in [ValheimLib ](https://github.com/Valheim-Modding/ValheimLib/blob/master/ValheimLib/Prefab.cs#L106)

### Additional context
I've developed a [mod](https://github.com/Igmat/ChestReloadedPlugin) that adds custom piece ‘SignedChest’. It is registered with following code:
```cs
GameObject signedLocker = assetBundle.LoadAsset<GameObject>("Assets/Pieces/SignedChest.prefab");
siqnedLocker.FixReferences();
GameObject cloned = signedLocker.InstantiateClone("SignedChest");
```
Which is called from namespace `ChestReloaded.Pieces` from class `SignedLocker` from method `AddSignedChestPiece` which ends up with the name of instance equal to `SignedChest_ChestReloaded_SigqnedLocker_AddSignedChestPiece(Clone)`.
After small refactoring where this code was moved to method `AddPrefab` loading world with placed pieces from previous mod version causes them to be destroyed as invalid prefabs, because now mod registers prefab with name  `SignedChest_ChestReloaded_SigqnedLocker_AddPrefab(Clone)` which differs from name of prefab in savegame.

It might be fixed with following line in mod code:
```cs
cloned.name = "SignedChest_ChestReloaded_SigqnedLocker_AddSignedChestPiece(Clone)";
```
But it seems like such problem shouldn't appear in first place.

**Comment by sirskunkalot** [comment]
Problem here is that InstantiateClone is meant for cloning vanilla prefabs, not custom ones. The UID (invoking method) is then appended to generate uniqueness. But agreed, should not be based on invoking method. Maybe just force the mod to name it via parameter. And it must be explained better.
