### ISSUE TITLE
Changelog, features, roadmap

### ISSUE THREAD

**Issue by raduschirliu** [Valheim-Modding/Jotunn#58]
We're currently not keeping track of changes at all in this repo. We should create some form of changelog markdown file documenting what we've done up to the initial release, and what feature will be available upon release.

Additionally, we should clean up (or honestly, probably could even entirely remove) the "features & roadmap" section from the README.

- [x] Features
- [x] Roadmap
- [x] Thunderstore README.md
- [x] Nexus page ?????
- [x] Begin curated changelog via a featurelist

**Comment by paddywaan** [comment]
Honestly, I'm not entirely sure it makes sense to compile a changelog for a release, this is basically a feature list which will be documented regardless by our docs/wiki/boilerplate. Changelog only makes sense when patch dates/iterations become relevant, which for the moment they are not.

I suppose a changelog makes sense if we were to take the features that both JL/VL implemented and were to strike through any feature removed, or point to the new interface provided, however I'm not entirely sure what purpose this would serve as this approach would likely be resolving the same issue that you mentioned in #57.

**Comment by Algorithman** [comment]
Regarding the nexus page, there is a markdown to bbcode converter

**Comment by paddywaan** [comment]
I found it :)

**Comment by Algorithman** [comment]
Isnt this done now? 5/5
