### ISSUE TITLE
feat: Add saving of custom skills into the Save Manager

### ISSUE THREAD

**Issue by raduschirliu** [Valheim-Modding/Jotunn#70]
Currently, only modded items are saved separately from player data. Would it be worth it to attempt to save modded player skills separately as well?

**Comment by paddywaan** [comment]
Yes, yes it would. If it is a simple naiive implementation then sure, include it in our release, but at this stage I'd rather push for release and worry more about code cleanup / docs than features.

**Comment by sirskunkalot** [comment]
item saving is disabled rn cause it causes lags on certain conditions. moved to v2.2

**Comment by MSchmoecker** [comment]
The SaveManger is now long disabled (since 2.0.12) and removed from code over time. There is now a solution for custom itemdata in vanilla and it's thus not need anymore.
Also having more separate save files will only make it harder to transfer saves and rollback backups.
